#!/bin/bash

# Loopback devices for kpartx

DEV=/dev/loop-control
mknod -m 660 $DEV c 10 237
chgrp disk $DEV

for i in `seq 0 7`; do
	DEV=/dev/loop$i
	mknod -m 660 $DEV b 7 $i
	chgrp disk $DEV
done

# tun device for making virtual NICs

mkdir -p /dev/net
mknod /dev/net/tun c 10 200

# Until I remember to patch TMMS

mkdir -p /var/log/tmms

exit 0
