#!/bin/bash

[ -z "$NETNAME" ] && echo "export NETNAME=something" >&1 && exit 1

set -u
NODE=$1		# hostname or number?
[ ${NODE#junk} = $NODE ] && NODE=node`printf "%02d" $NODE`
echo "Prompt for window name:      ctl-a then '"
echo "Navigate list of windows:    ctl-a then \""
echo "Quit (detach):               ctl-a then d"
sleep 2
screen -r $NETNAME -p $1
reset
exit 0
