#!/bin/bash

# Start multiple FAME nodes.
# Args are "all" or a list of nodenumbers range 1-40.

if [ $# -eq 0 -o "$1" = "-?" ]; then
	echo "usage: $0 all | nodenum [nodenum...]"
	exit 0
fi
if [ $1 = all ]; then
	NODES=`seq 1 40`
else
	NODES="$@"	# These aren't qualified in any way
fi

[ -z "$NETNAME" ] && echo "export NETNAME=something" >&1 && exit 1
[ -z "$FAM" ] && echo "export FAM=something" >&1 && exit 1

set -u

STARTNODE=startnode.arm		# Hardcoded now; in the future, who knows?

###########################################################################
# What's already running?

N=`pgrep -a qemu-system-aar | grep $NETNAME | wc -l` 
[ $N -ne 0 ] && echo "$N node(s) already running on $NETNAME" >&2 && exit 1

SCREEN=`screen -list | grep $NETNAME`
[ "$SCREEN" ] && echo "screen is already running $SCREEN" >&2 && exit 1

###########################################################################
# Go.  

screen -S $NETNAME -dm		# Session name, detached
for N in $NODES; do
	TITLE=node`printf "%02d" $N`
	screen -S $NETNAME -X screen -t $TITLE $STARTNODE $N
done

echo "Attach last node from shell: screen -r $NETNAME"
echo "Attach nodeXX from shell:    screen -r $NETNAME -p nodeXX"
echo "Prompt for window name:      ctl-a then '"
echo "Navigate list of windows:    ctl-a then \""
echo "Quit (detach):               ctl-a then d"

exec waitnodes $NODES
