#!/bin/bash

# Start multiple FAME nodes.
# Args are "all" or a list of nodenumbers range 1-40.

if [ $# -eq 0 -o "$1" = "-?" ]; then
	echo "usage: $0 all | nodenum [nodenum...]"
	exit 0
fi
if [ $1 = all ]; then
	NODES=`seq 1 40`
else
	NODES="$@"	# These aren't qualified in any way
fi

[ -z "$NETNAME" ] && echo "export NETNAME=something" >&1 && exit 1
[ -z "$FAM" ] && echo "export FAM=something" >&1 && exit 1

set -u

###########################################################################
# What's already running?

N=`pgrep -a qemu-system-aar | grep $NETNAME | wc -l` 
[ $N -ne 0 ] && echo "$N node(s) already running on $NETNAME" >&2 && exit 1

SCREEN=`screen -list | grep $NETNAME`
[ "$SCREEN" ] && echo "screen is already running $SCREEN" >&2 && exit 1

###########################################################################
# Go

screen -S $NETNAME -dm		# Session name, detached
for N in $NODES; do
	TITLE=node`printf "%02d" $N`	# Haven't got -t $TITLE to work yet
	screen -S $NETNAME -X screen famenode.arm $N
done

exec waitnodes $NODES
