#!/bin/bash

###########################################################################
# Wait for ping and ssh responses, no extra tools required.  Well, ping :-).
# Command line processing; usually called from startnodes.

NODES="$@"
N_WANTED=$#

[ -z "$NETNAME" ] && echo "export NETNAME=something" >&1 && exit 1

set -u

function all_running() {	# Optional $1 means wait
    while true; do
	N_RUNNING=`pgrep -a qemu-system-aar | grep $NETNAME | wc -l`
	let DEAD=$N_WANTED-$N_RUNNING
	[ $DEAD -eq 0 ] && return
	[ $# -eq 0 ] && echo "$DEAD qemu(s) are not running" >&2 && exit 1
	echo "Waiting for $DEAD qemu(s) to start..."
	sleep 1
    done
}

###########################################################################
# Main

all_running wait	# settling time if called from startnodes

HOSTNAMES=`for N in $NODES; do printf "node%02d " $N; done`

WAITING=$HOSTNAMES
START=`date +%s`
while [ "$WAITING" ]; do
    all_running
    WAITING=
    echo -en "\nPing"
    for H in $HOSTNAMES; do	# yeah do them all each time
	echo -n " $H"
	ping -c1 $H >/dev/null 2>&1
	[ $? -ne 0 ] && WAITING="$WAITING $H" && echo -n " (no ping)"
	echo -n ";"
    done
    echo 
    [ "$WAITING" ] && echo "Ping failed on $WAITING" && sleep 3
done

WAITING=$HOSTNAMES
while [ "$WAITING" ]; do
    END=`date +%s`
    let ELAPSED=$END-$START
    echo -e "\n$ELAPSED seconds"

    all_running
    WAITING=
    echo -en "\nRe-ping and test sshd for"
    for H in $HOSTNAMES; do	# yeah do them all each time
	# Either kernel panic (maybe a dropped TFTP packet?) or systemd
	# hang at "bring up network interface"
	echo -n " $H"
	ping -c1 $H >/dev/null 2>&1
	if [ $? -ne 0 ]; then
	    echo -n " (no ping)"
	    WAITING="$WAITING $H"
	else
	    # From the Google.  First time, the timeout is about 20 seconds.
	    # Second time is about 3.
	    (echo > /dev/tcp/$H/22) >/dev/null 2>&1
	    if [ $? -ne 0 ]; then
		echo -n " (no ssh)"
		WAITING="$WAITING $H"
	    fi
	fi
	echo -n ";"
    done
    [ "$WAITING" ] && echo -e "\nSSH failed on $WAITING" && sleep 5
done
echo
END=`date +%s`
let ELAPSED=$END-$START
echo "$ELAPSED seconds total (ping + ssh)"

exit 0
