#!/bin/bash
#DEBHELPER#
set -e

TMMS_DIR=/usr/lib/python3/dist-packages/tmms/

if [ -d "$TMMS_DIR" ]; then
    echo "Removing dist-packages/tmms/ with a postrm script..."
    rm -r $TMMS_DIR
fi


TMMS_DIR=/var/lib/tmms/
if [ -d "$TMMS_DIR" ]; then
    echo "Removing $TMMS_DIR with a postrm script..."
    rm -r $TMMS_DIR
fi


if [ -e "/etc/tmms" ]; then
    echo "Removing /etc/tmms"
    rm /etc/tmms
fi

# --------- UNLINK /usr/bin/ stuff ---------

if [ -e "/usr/bin/tm-manifest" ]; then
    unlink /usr/bin/tm-manifest
fi
if [ -e "/usr/bin/tm-manifest-server" ]; then
    unlink /usr/bin/tm-manifest-server
fi
if [ -e "/usr/bin/tm-manifest-setup" ]; then
    unlink /usr/bin/tm-manifest-setup
fi
