#!/bin/bash
#DEBHELPER#
set -e

#. /var/lib/dpkg/info/tm-manifest.post-args-parser $1

TMMS_SRC=/usr/lib/python3/dist-packages/tmms
TMMS_CFG=/etc/tmms

IsUpgrade=false
IsRemove=false
IsPurge=false
IsFailedUpgrade=false
IsAbortRemove=false

for arg in "$@"
do
case $arg in
    remove)
        IsRemove=true
        shift
    ;;
    upgrade)
        IsUpgrade=true
        shift
    ;;
    purge)
        IsPurge=true
        shift
    ;;
    failed-upgrade)
        IsFailedUpgrade=true
        shift
    ;;
    abort-remove)
        IsAbortRemove=true
        shift
    ;;
    *)
    ;;
esac
done


if [ "$IsRemove" ]; then
    if [ -d "$TMMS_SRC" ]; then
        echo " --- postrm remove: removing dist-packages/tmms/ with a postrm script... --- "
        rm -r $TMMS_SRC
    fi

    # --------- UNLINK /usr/bin/ stuff ---------
    echo " --- postrm remove: unlinking /usr/bin/tm-manifest* files --- "

    if [ -e "/usr/bin/tm-manifest" ]; then
        unlink /usr/bin/tm-manifest
    fi
    if [ -e "/usr/bin/tm-manifest-server" ]; then
        unlink /usr/bin/tm-manifest-server
    fi

fi # if IsRemove

if [ "$IsPurge" == true ]; then
    if [ -e "$TMMS_CFG" ]; then
        echo "Moving $TMMS_CFG to /etc/tmms.purge with a postrm script..."
        mv $TMMS_CFG ${TMMS_CFG}.purge
    fi
fi # if IsRemove

if [ "$IsUpgrade" == true ]; then
    echo "postrm upgrade doing nothing... Next."
fi

if [ "$IsFailedUpgrade" == true ]; then
    echo "postrm failed-upgrade is not handeled... Next."
fi

if [ "$IsAbortUpgrade" == true ]; then
    echo "postrm abort-upgrade is not handeled... Next."
fi
