#!/bin/bash
# During the package install, post,pre scripts can and will be called with
# different arguments for different packaging state: install, update, purge...
# Reference for the call flow: https://wiki.debian.org/MaintainerScripts

set -e

TMMS_SRC=/usr/lib/python3/dist-packages/tmms
TMMS_CFG_DIR=/etc/tmms

IsInstall=false
IsAbortInstall=false
IsConfigure=false

IsRemove=false
IsPurge=false
IsAbortRemove=false

for arg in "$@"
do
case $arg in
    install)
        IsInstall=true
        shift
    ;;
    abort-install)
        IsAbortInstall=true
        shift
    ;;
    configure)
        IsConfigure=true
        shift
    ;;
    remove)
        IsRemove=true
        shift
    ;;
    purge)
        IsPurge=true
        shift
    ;;
    abort-remove)
        IsAbortRemove=true
        shift
    ;;
    *)
    ;;
esac
done
