#!/bin/bash
#DEBHELPER#
set -e

#. /var/lib/dpkg/info/tm-manifest.post-args-parser $1
TMMS_SRC=/usr/lib/python3/dist-packages/tmms

IsUpgrade=false
IsRemove=false
IsPurge=false
IsFailedUpgrade=false
IsAbortRemove=false


for arg in "$@"
do
case $arg in
    upgrade)
        IsUpgrade=true
        shift
    ;;
    remove)
        IsRemove=true
        shift
    ;;
    purge)
        IsPurge=true
        shift
    ;;
    failed-upgrade)
        IsFailedUpgrade=true
        shift
    ;;
    abort-remove)
        IsAbortRemove=true
        shift
    ;;
    *)
    ;;
esac
done



if [ "$IsRemove" == true ]; then

    bin/systemctl stop tm-manifest-server
    bin/systemctl disable tm-manifest-server

    if [ -e "/lib/systemd/system/tm-manifest-server.service" ]; then
        rm /lib/systemd/system/tm-manifest-server.service
    fi
    if [ -e "/usr/default/tm-manifest-server" ]; then
        rm /usr/default/tm-manifest-server
    fi

    systemctl daemon-reload
fi


if [ "$IsUpgrade" == true ]; then
    echo " --- prerm upgrade: moving ${TMMS_SRC} to ${TMMS_SRC}.upgrade --- "
    mv $TMMS_SRC ${TMMS_SRC}.upgrade   # Backup the original tmms dir (to restore on fail)
fi


if [ "$IsFailedUpgrade" == true ]; then
    echo " --- prerm failed-upgrade: moving ${TMMS_SRC}.upgrade to ${TMMS_SRC} --- "
    mv ${TMMS_SRC}.upgrade $TMMS_SRC
fi

if [ "$IsAbortRemove" == true ]; then
    echo " --- prerm abort-remove: is not handlede... skipping. ---"
fi
