#!/bin/bash
#DEBHELPER#

#. /var/lib/dpkg/info/tm-manifest.post-args-parser $1
TMMS_SRC=/usr/lib/python3/dist-packages/tmms

IsUpgrade=false
IsRemove=false
IsPurge=false
IsFailedUpgrade=false
IsAbortRemove=false


for arg in "$@"
do
case $arg in
    upgrade)
        IsUpgrade=true
        shift
    ;;
    remove)
        IsRemove=true
        shift
    ;;
    purge)
        IsPurge=true
        shift
    ;;
    failed-upgrade)
        IsFailedUpgrade=true
        shift
    ;;
    abort-remove)
        IsAbortRemove=true
        shift
    ;;
    *)
    ;;
esac
done


# Flag to indicate server is running as a daemon
ps -ef | grep tm-manifest-server | grep -v grep
if [ $? -eq "0" ]; then
    # Will flag the restart of the service later on during the update
    #touch /tmp/tm-manifest-server.restart
    echo " --- !!! WARNING !!! --- "
    echo " --- Shutting down manifesting daemon.... it will not be restarted on update! --- "
    echo " --- A systemctl service of the manifesting server will be started instead! --- "
    tm-manifest-server --daemon-stop
fi

# Flag to indicate server is running as systemctl service
bin/systemctl status tm-manifest-server | grep running
if [ $? -eq "0" ]; then
    #touch /tmp/tm-manifest-server.restart-service
    echo " --- !!! WARNING !!! --- "
    echo " --- systemctl service will be stopped and restarted on update! --- "
    bin/systemctl stop tm-manifest-server
fi


if [ "$IsRemove" == true ]; then

    bin/systemctl disable tm-manifest-server

    if [ -e "/lib/systemd/system/tm-manifest-server.service" ]; then
        rm /lib/systemd/system/tm-manifest-server.service
    fi
    if [ -e "/usr/default/tm-manifest-server" ]; then
        rm /usr/default/tm-manifest-server
    fi

    systemctl daemon-reload

    # Remove restart file, since it is not needed due to the full remove of
    # the package
    #[ -f /tmp/tm-manifest-server.restart ] && rm /tmp/tm-manifest-server.restart
    #[ -f /tmp/tm-manifest-server.restart-service ] && rm /tmp/tm-manifest-server.restart-service
fi


if [ "$IsUpgrade" == true ]; then
    echo " --- prerm upgrade: doing nothing... --- "
fi


if [ "$IsFailedUpgrade" == true ]; then
    echo " --- prerm failed-upgrade: doing nothing... (handled by postrm) --- "
fi


if [ "$IsAbortRemove" == true ]; then
    echo " --- prerm abort-remove: is not handlede... skipping. ---"
fi
