#!/bin/bash
#DEBHELPER#
set -e

. /var/lib/dpkg/info/tm-manifest.post-args-parser $1

if [ "$IsRemove" ]; then

    bin/systemctl stop tm-manifest-server
    bin/systemctl disable tm-manifest-server

    rm /lib/systemd/system/tm-manifest-server.service
    rm /usr/default/tm-manifest-server

    systemctl daemon-reload
fi


if [ "$IsUpgrade" ]; then
    mv $TMMS_SRC $TMMS_SRC.backup   # Backup the original tmms dir (to restore on fail)
fi
