#!/usr/bin/dh-exec

blueprints/         usr/lib/python3/dist-packages/tmms/
configs/            usr/lib/python3/dist-packages/tmms/
static/             usr/lib/python3/dist-packages/tmms/
templates/          usr/lib/python3/dist-packages/tmms/
tm_cmd/             usr/lib/python3/dist-packages/tmms/
unittests/          usr/lib/python3/dist-packages/tmms/
utils/              usr/lib/python3/dist-packages/tmms/
tmms                usr/lib/python3/dist-packages/tmms/
README*             usr/lib/python3/dist-packages/tmms/
*.py                usr/lib/python3/dist-packages/tmms/
systemd/            usr/lib/python3/dist-packages/tmms/
docs/*              usr/share/man/man8/
systemd/systemd_tmms-server            => usr/default/tm-manifest-server
systemd/systemd_tmms-server.service    => lib/systemd/system/tm-manifest-server.service

debian/post-args-parser => /var/lib/dpkg/info/tm-manifest.post-args-parser
