.TH tm-manifest-server "8" "2016" "The Machine" "Manifesting API Server"

.SH NAME
tm-manifest-server \- Control the Manifesting service of an instance of The Machine

.SH SYNOPSIS
\fBtm-manifest-server\fP [options] <directive> [arguments]

.SH DESCRIPTION
\fBtm-manifest-server\fP is an api server that is responsible for listening to
client's requests.


.SH DIRECTIVES

\fP
.SH OPTIONS
.PP

.TP
\fB-?\fR
Print a synopsis of all options and hints

.TP
\fB-d\fR
Turn on debugging

.TP
\fB-v\fR
Make it talk

\fP
.SH FILES
Server is using /etc/tmms config file that is intended to be customizible by the
user if needed per manifesting instance

.SH BUGS
None that we know of.  Today.  Between noon and 1 pm.
