.TH tm-manifest-server "8" "2016" "The Machine" "Manifesting API Server"

.SH NAME
tm-manifest-server \- Control the Manifesting service of an instance of The Machine

.SH SYNOPSIS
\fBtm-manifest-server\fP [options] <directive> [arguments]

.SH DESCRIPTION
\fBtm-manifest-server\fP is an api server that is responsible for listening to
client's requests. Use "tm-manifest" command line tool to talk to the API.


.SH DIRECTIVES

\fP
.SH OPTIONS
.PP

.TP
-D, --daemon-start
Run Manifesting Server as a daemon (background process)

.TP
--daemon-status
Get the status of the Manifesting Server process (is it running or not).

.TP
--daemon-stop
Stop manifesting server if it is running.

.TP
--daemon-restart
Restart Manifesting Server.

.TP
--start-dnsmasq
Restarts dnsmasq configuration based on the /etc/tmms config.

.TP
-?
Print a synopsis of all options and hints

.TP
-d
Turn on debugging

.TP
-v
Make it talk

\fP
.SH FILES
Server is using \fB/etc/tmms\fR config file that is intended to be customizible
by the user if needed per manifesting instance.

/etc/tmconfig is a core "nodes topology" config file. It usually comes from a
wonder land, but can also be generated using tm-librarian utils, which is a
dependency for tm-manifesting.


.SH BUGS
None that we know of.  Today.  Between noon and 1 pm.
