.TH tm-manifest-setup "8" "2016" Manifesting setup script"

.SH NAME
\fBtm-manifest-setup\fP \- setup script for the manifesting environment.

.SH SYNOPSIS
\fBtm-manifest-server\fP [options] <directive> [arguments]

.SH DESCRIPTION
\fBtm-manifest-setup\fP - Helps to configure your environment in automated fashion.


.SH DIRECTIVES

\fP
.SH OPTIONS
.PP

.TP
\fB-?\fR
 Print a synopsis of all options and hints

.TP
\f-c, --config\fR
 Configuration file to be used. Default=/etc/tmms

.TP
\fB--debug\fR
 Turn on flask debugging.

.TP
\fB--dry-run\fR
 No action; simulation of events.

.TP
\fB-P, --packaging\fR
 This flag should only be set by post-setup scripts in
 Debian installer. Using it while trying to run from
 the git repo will result in a non-functioning environment.

.TP
\fB-v, --verbose\fR
 Verbose option for the setup process.

.SH BUGS
None that we know of.  Today.  Between noon and 1 pm.
